name: "Kubernetes Setup"
description: "Install kubectl and configure kubeconfig"

inputs:
  kubeconfig:
    description: "Base64-encoded kubeconfig"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install kubectl
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Set up kubeconfig
      shell: bash
      run: |
        mkdir -p $HOME/.kube
        echo "${{ inputs.kubeconfig }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
